[Display]
preinstall=사전 구성
user_defined=사용자 구성

[TypeCount]
Preinstall=8

[Preinstall0]
type=0
text=기밀
index=0
picture=
preview=Preinstall0
offsetUnit=3
voffset=0.0
hoffset=0.0
valign=1
halign=1
scale=70
opacity=10
rotation=45
fontSize=540
relative=1
fontName=Arial
fontRed=0
fontGreen=0
fontBlue=0
fontUnderline=0
fontBold=0
fontItalic=0
indexArray=
start=-1
end=-1
odd=1
even=1
tilemode=0
lines=0

[Preinstall1]
type=0
text=극비
index=1
picture=
preview=Preinstall1
offsetUnit=3
voffset=0.0
hoffset=0.0
valign=1
halign=1
scale=70
opacity=10
rotation=45
fontSize=540
relative=1
fontName=Arial
fontRed=0
fontGreen=0
fontBlue=0
fontUnderline=0
fontBold=0
fontItalic=0
indexArray=
start=-1
end=-1
odd=1
even=1
tilemode=0
lines=0

[Preinstall2]
type=0
text=무단 복제 금지
index=2
picture=
preview=Preinstall2
offsetUnit=3
voffset=0.0
hoffset=0.0
valign=1
halign=1
scale=70
opacity=10
rotation=45
fontSize=540
relative=1
fontName=Arial
fontRed=0
fontGreen=0
fontBlue=0
fontUnderline=0
fontBold=0
fontItalic=0
indexArray=
start=-1
end=-1
odd=1
even=1
tilemode=0
lines=0

[Preinstall3]
type=0
text=내부 자료
index=3
picture=
preview=Preinstall3
offsetUnit=3
voffset=0.0
hoffset=0.0
valign=1
halign=1
scale=70
opacity=10
rotation=45
fontSize=540
relative=1
fontName=Arial
fontRed=0
fontGreen=0
fontBlue=0
fontUnderline=0
fontBold=0
fontItalic=0
indexArray=
start=-1
end=-1
odd=1
even=1
tilemode=0
lines=0

[Preinstall4]
type=0
text=기밀
index=4
picture=
preview=Preinstall4
offsetUnit=2
voffset=0
hoffset=0
valign=1
halign=1
scale=100
opacity=10
rotation=45
fontSize=540
relative=0
fontName=Arial
fontRed=0
fontGreen=0
fontBlue=0
fontUnderline=0
fontBold=0
fontItalic=0
indexArray=
start=-1
end=-1
odd=1
even=1
tilemode=3
lines=3

[Preinstall5]
type=0
text=극비
index=5
picture=
preview=Preinstall5
offsetUnit=2
voffset=0
hoffset=0
valign=1
halign=1
scale=100
opacity=10
rotation=45
fontSize=540
relative=0
fontName=Arial
fontRed=0
fontGreen=0
fontBlue=0
fontUnderline=0
fontBold=0
fontItalic=0
indexArray=
start=-1
end=-1
odd=1
even=1
tilemode=3
lines=3

[Preinstall6]
type=0
text=무단 복제 금지
index=6
picture=
preview=Preinstall6
offsetUnit=2
voffset=0
hoffset=0
valign=1
halign=1
scale=100
opacity=10
rotation=45
fontSize=540
relative=0
fontName=Arial
fontRed=0
fontGreen=0
fontBlue=0
fontUnderline=0
fontBold=0
fontItalic=0
indexArray=
start=-1
end=-1
odd=1
even=1
tilemode=3
lines=3

[Preinstall7]
type=0
text=내부 자료
index=7
picture=
preview=Preinstall7
offsetUnit=2
voffset=0
hoffset=0
valign=1
halign=1
scale=100
opacity=10
rotation=45
fontSize=540
relative=0
fontName=Arial
fontRed=0
fontGreen=0
fontBlue=0
fontUnderline=0
fontBold=0
fontItalic=0
indexArray=
start=-1
end=-1
odd=1
even=1
tilemode=3
lines=3

;730A7EABABD020B0A3F24134E6BD6A18476EA4A71DE68B34D11252F860F24717ACEB882943AB6E7E40D74FF563B7A9E2FD085DA7E12FE923E2DD0D08F071BA2B