[Display]
preinstall=사전 설정 워터마크
Custom=사용자 지정 워터마크

[TypeCount]
Preinstall=4

[Preinstall0]
type=0
text=기밀
fontName=Arial
textAngle=-45
fontSize=12
textScale=100
textOpacity=50
preview=CONFIDENTIAL

[Preinstall1]
type=0
text=일급 비밀
fontName=Arial
textAngle=-45
fontSize=12
textScale=100
textOpacity=50
preview=TOP_SECRET

[Preinstall2]
type=0
text=복사 금지
fontName=Arial
textAngle=-45
fontSize=12
textScale=100
textOpacity=50
preview=DO_NOT_COPY

[Preinstall3]
type=0
text=내부 문서
fontName=Arial
textAngle=-45
fontSize=12
textScale=100
textOpacity=50
preview=INTERNAL_DOCUMENT

;AE2BD131BF3A0C4A2378CD49797441455E8455C8833996D4689565719A745F93093404B68DEFBC87A388AA2B57341A26487C1671F4CA14594378316DBC70E54E